name: nanocosm_image
channels:
  - conda-forge
  - fastchan
  - bioconda
  - defaults
dependencies:
  - python=3.10.4
  - opencv-python-headless=4.6.0.66
  - imageio=2.21.3
  - pandas=1.4.4
  - scipy=1.9.1
  - progress=1.6
  - matplotlib=3.5.3
  - exifread=3.0.0
  - imutils=0.5.4
