name: nanocosm_image
channels:
  - conda-forge
  - fastchan
  - bioconda
  - defaults
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.6.15.1
  - certifi=2022.6.15.1
  - cycler=0.11.0
  - exifread=3.0.0
  - fonttools=4.37.1
  - freetype=2.10.4
  - icu=68.2
  - imageio=2.21.3
  - imutils=0.5.4
  - intel-openmp=2022.1.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libdeflate=1.10
  - libffi=3.4.2
  - liblapack=3.9.0
  - libpng=1.6.37
  - libsqlite=3.39.3
  - libtiff=4.3.0
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2022.0.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - numpy=1.23.3
  - olefile=0.46
  - opencv-python-headless=4.6.0.66
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pillow=8.4.0
  - pip=22.2.2
  - progress=1.6
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.2.1
  - qt=5.12.9
  - scipy=1.9.1
  - setuptools=65.3.0
  - six=1.16.0
  - sqlite=3.39.3
  - tbb=2021.5.0
  - tk=8.6.12
  - tornado=6.2
  - tzdata=2022c
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - vc=14.2
  - vs2015_runtime=14.29.30139
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - rawpy==0.17.2 [--no-dependencies]
